# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IntelliGeo
                                 A QGIS plugin
 IntelliGeo is QGIS plugin that facilitates interaction with Large Language Models in QGIS environment
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-01-18
        copyright            : (C) 2024 by GIP Department, Faculty ITC, University of Twente
        email                : m.farnaghi@utwente.nl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

import os
import sys

scriptDir = os.path.dirname(os.path.abspath(__file__))
extpluginDir = os.path.join(scriptDir, "extlibs")

if not os.path.exists(extpluginDir):
    os.makedirs(extpluginDir, exist_ok=True)

if extpluginDir not in sys.path:
    sys.path.insert(0, extpluginDir)


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """
    Load IntelliGeo class from file IntelliGeo.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """

    from .intelli_geo import IntelliGeo

    return IntelliGeo(iface)
