name: Deploy MkDocs site

# Run the workflow when code is pushed to the 'main' branch
on:
  push:
    branches:
      - main # or the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Intall required tools on Ubuntu
        run: sudo apt-get update && sudo apt-get install -y lsb-release && sudo apt-get clean all

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -U mkdocs mkdocs-material mkdocs-bootswatch

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force  # Build and deploy the site to GitHub Pages
